Synapxe-DNA/azure-conversational-assistant

app/frontend-healthier-me/src/app/services/chat-message/chat-message.service.ts
app/frontend-healthier-me/src/app/services/convo-broker/convo-broker.service.spec.ts
app/frontend-healthier-me/src/app/services/convo-broker/convo-broker.service.ts
app/frontend-healthier-me/src/app/services/endpoint/endpoint.service.ts
app/frontend-healthier-me/src/app/types/profile.type.ts
app/frontend-healthier-me/src/app/types/responses/chat-response.type.ts
app/frontend-healthier-me/src/app/types/responses/response-status.type.ts
app/frontend-healthier-me/src/app/types/responses/voice-response.type.ts

- Created method signatures for convobroker and endpoint service
- Updated typing for profile type and general profile

Frontend convo broker

---

app/Makefile
app/backend/app.py
app/backend/speech/speech_to_text.py

- Text to speech is using ample text currently

Added tts and stt into /voice endpoint

---

app/backend/app.py
app/backend/models/voice.py
app/dev.sh
app/frontend-healthier-me/src/app/app.config.ts
app/frontend-healthier-me/src/app/components/navbar/navbar-profile-links/navbar-profile-link.component.ts
app/frontend-healthier-me/src/app/components/text/text-system/text-system.component.spec.ts
app/frontend-healthier-me/src/app/components/text/text.component.ts
app/frontend-healthier-me/src/app/components/voice/voice.component.ts
app/frontend-healthier-me/src/app/components/waveform/waveform.component.ts
app/frontend-healthier-me/src/app/services/audio-player/audio-player.service.ts
app/frontend-healthier-me/src/app/services/convo-broker/convo-broker.service.ts
app/frontend-healthier-me/src/app/services/endpoint/endpoint.service.ts
app/frontend-healthier-me/src/app/types/api/api-chat-history.type.ts
app/frontend-healthier-me/src/app/types/api/api-profile.type.ts
app/frontend-healthier-me/src/app/types/api/requests/voice-request.type.ts
app/frontend-healthier-me/src/app/types/api/response/api-voice-response.type.ts
app/frontend-healthier-me/src/app/types/message.type.ts
app/frontend-healthier-me/src/app/types/profile.type.ts
app/frontend-healthier-me/src/app/types/responses/voice-response.type.ts
app/frontend-healthier-me/src/app/utils/audio-recorder.ts
app/frontend-healthier-me/src/app/utils/base-64-to-blob.ts
app/frontend-healthier-me/src/app/utils/typed-form-data.ts

**Backend**
- Updated models to reflect base 64 audio file to be returned
- Fixed attribute name when referencing POST req
- currently returns audio given from frontend as base64 audio
**Frontend**
- Refactored types for "system" role to "assistant"
- Added response types from API endpoint
- Added SR support to handle streaming text responses
- Added ConvoBroker to manage ALL chat/voice interaction
- Updated waveform to display waveform of response audio
- Added supporting functions/methods
**Misc**
`dev.sh` will watch changes and build the bundle to be served by the backend

Frontend integrate endpoints (voice)

---

app/frontend-healthier-me/src/app/components/text/text-input/text-input.component.ts
app/frontend-healthier-me/src/app/services/convo-broker/convo-broker.service.ts
app/frontend-healthier-me/src/app/services/endpoint/endpoint.service.ts
app/frontend-healthier-me/src/app/types/api/api-source.type.ts
app/frontend-healthier-me/src/app/types/api/requests/chat-request.type.ts
app/frontend-healthier-me/src/app/types/api/response/api-chat-response.type.ts
app/frontend-healthier-me/src/app/types/responses/chat-response.type.ts

- Created chat methods in convo broker
- Created endpoint handlers in endpoint service
- Shifted chat message sending logic from text-input to convo broker

Frontend integrate endpoints (chat)

---

app/backend/approaches/approach.py
app/backend/approaches/chatapproach.py
app/backend/approaches/chatreadretrieveread.py

Added profile parameter

---

app/frontend-healthier-me/src/app/components/text/text-input/text-input.component.ts
app/frontend-healthier-me/src/app/components/text/text.component.ts
app/frontend-healthier-me/src/app/services/profile/profile.service.ts

Fixed a bug where the chat history was not being showed properly for the profile.

Frontend -- fixed bug for loading chat for general profile

---

app/frontend-healthier-me/src/app/components/text/text-system/text-system.component.html
app/frontend-healthier-me/src/app/components/text/text-user/text-user.component.html
app/frontend-healthier-me/src/app/components/text/text.component.html
app/frontend-healthier-me/src/app/components/text/text.component.ts
app/frontend-healthier-me/src/app/components/voice/voice.component.html
app/frontend-healthier-me/src/app/components/voice/voice.component.ts
app/frontend-healthier-me/src/app/services/preference/preference.service.ts
app/frontend-healthier-me/src/app/types/configs/preference-keys.type.ts

- Updated styling to use text.component in voice
- Added preference to show and hide chat history

Frontend -- shows conversation on the left of voice

---

app/frontend-healthier-me/src/app/app.component.ts
app/frontend-healthier-me/src/app/components/text/text.component.html
app/frontend-healthier-me/src/app/components/voice/voice.component.ts
app/frontend-healthier-me/src/app/components/waveform/waveform.component.ts
app/frontend-healthier-me/src/app/layouts/main-layout/main-layout.component.ts
app/frontend-healthier-me/src/app/services/convo-broker/convo-broker.service.ts
app/frontend-healthier-me/src/app/services/endpoint/endpoint.service.ts
app/frontend-healthier-me/src/app/services/profile/profile.service.ts

- Updated how voice profile is set for sending voice message (activatedURL only available in lowest router)
- Updated endpoint handling of response
- Updated UI for waveform

Staging message fix

---

app/frontend-healthier-me/src/app/services/vad/vad.service.ts

Fixed error by re-initialising `SpeechRecognition` on error and on complete

Fix VAD dropping out

---

app/backend/utils/utils.py
app/frontend-healthier-me/src/app/services/endpoint/endpoint.service.ts
app/frontend-healthier-me/src/app/services/vad/vad.service.ts
app/frontend-healthier-me/src/app/types/api/requests/chat-request.type.ts
app/frontend-healthier-me/src/app/types/api/response/api-chat-response.type.ts

- Updated frontend schemas to match backend
- Updated backend to respond with only text on `/chat/stream`, to mitigate error while parsing stream buffer
- QoL improvements in VAD

Frontend chat integration and QoL improvements

---

.github/workflows/frontend.yaml
app/frontend-healthier-me/package.json

- Updated action to only run when changes in files for healthier me frontend
- Updated it to use the NPM lint command in package.json
- Updated package.json to ignore .angular files

Updated lint actions for frontend

---

app/backend/app.py
app/backend/blueprints/backend_blueprint/chat.py
app/backend/blueprints/backend_blueprint/speech.py
app/backend/blueprints/backend_blueprint/upload.py
app/backend/blueprints/backend_blueprint/voice.py
app/frontend-healthier-me/src/app/components/text/text-followup/text-followup.component.html
app/frontend-healthier-me/src/app/components/text/text-followup/text-followup.component.spec.ts
app/frontend-healthier-me/src/app/components/text/text-followup/text-followup.component.ts
app/frontend-healthier-me/src/app/components/text/text-tts/text-tts.component.ts
app/frontend-healthier-me/src/app/components/text/text.component.html
app/frontend-healthier-me/src/app/components/text/text.component.ts
app/frontend-healthier-me/src/app/services/chat-followup/chat-followup.service.spec.ts
app/frontend-healthier-me/src/app/services/chat-followup/chat-followup.service.ts
app/frontend-healthier-me/src/app/services/endpoint/endpoint.service.ts
app/frontend-healthier-me/src/app/types/api/requests/speech-request.type.ts
app/frontend-healthier-me/src/app/types/follow-up.type.ts

- Abstract out voice,speech,chat, upload into different files/blueprints

Refactor app.py

---

app/backend/blueprints/backend_blueprint/transcription.py
app/backend/blueprints/backend_blueprint/voice.py
app/backend/models/language.py
app/backend/speech/text_to_speech.py
app/backend/utils/utils.py

- Solution: Force the TTS to the specified language. Hence no translation is required on our end

Fix TTS issue with numbers

---

app/backend/models/feedback.py
app/frontend-healthier-me/src/app/components/voice-mobile/voice-message/voice-message.component.ts
app/frontend-healthier-me/src/app/components/voice-mobile/voice-mobile.component.html
app/frontend-healthier-me/src/app/components/voice-mobile/voice-mobile.component.ts

- Textbox is now pulsing instead of background colour

Update the pulsing animation

---

app/frontend-healthier-me/src/app/components/voice-mobile/voice-mobile.component.ts

possible fix for callback taking too long, outrunning the user activation period

userActivation check

---

app/backend/blueprints/frontend_blueprint/frontend.py
app/frontend-healthier-me/src/app/components/voice-mobile/voice-mobile.component.html
app/frontend-healthier-me/src/app/components/voice-mobile/voice-mobile.component.ts
app/frontend-healthier-me/src/app/services/convo-broker/convo-broker.service.ts
app/frontend-healthier-me/src/index.html

reverted sendvoice refactor
added permissions policy to index.html and backend http header

reverted changes

---

app/frontend-healthier-me/src/app/components/navbar/navbar.component.ts
app/frontend-healthier-me/src/app/components/voice-mobile/voice-message/voice-message.component.ts

Voice page text field pulsing now correctly synced with audio from speakers. 
Previously was using microphone input for audio levels.

Pulsing Fix

---

app/frontend-healthier-me/src/app/components/navbar-mobile/navbar-mobile.component.html
app/frontend-healthier-me/src/app/components/navbar/navbar-profile-links/navbar-profile-link.component.html
app/frontend-healthier-me/src/app/components/navbar/navbar-profile-links/navbar-profile-link.component.ts
app/frontend-healthier-me/src/app/components/voice-mobile/voice-annotation/voice-annotation.component.css
app/frontend-healthier-me/src/app/components/voice-mobile/voice-annotation/voice-annotation.component.html
app/frontend-healthier-me/src/app/components/voice-mobile/voice-message/voice-message.component.css
app/frontend-healthier-me/src/app/components/voice-mobile/voice-message/voice-message.component.html
app/frontend-healthier-me/src/app/components/voice-mobile/voice-message/voice-message.component.ts
app/frontend-healthier-me/src/app/pages/create-profile/create-profile.component.html
app/frontend-healthier-me/src/app/services/chat-message/chat-message.service.ts
app/frontend-healthier-me/src/app/services/convo-broker/convo-broker.service.ts
app/frontend-healthier-me/src/app/services/endpoint/endpoint.service.ts

Added max age, profile pic and font slider.

Fixed feedback bug, added new components

---

bicepconfig.json
infra/core/security/keyvault-access.bicep
infra/core/security/keyvault.bicep
infra/main.bicep
infra/main.parameters.json

Added key vault to store credentials for authentication. To be used by external vendors for adversarial testing.

Updated bicep file to create key vaults for API authentication

---

notebooks/azure_data_actual.ipynb
notebooks/azure_data_testing.ipynb
notebooks/azure_search_tutorial_v3.0.ipynb

-Added comments to the lines of codes in the notebook for azure search index after the meeting with Joycelyn and Yadanar.

Added comments for the codes

---

app/backend/app.py
app/backend/authentication/authenticator.py
app/backend/blueprints/backend_blueprint/chat.py
app/backend/blueprints/backend_blueprint/feedback.py
app/backend/blueprints/backend_blueprint/login.py
app/backend/blueprints/backend_blueprint/speech.py
app/backend/blueprints/backend_blueprint/voice.py
app/backend/database/user_database.py
app/backend/models/account.py
app/backend/models/payload.py
app/backend/utils/utils.py
app/frontend-healthier-me/src/app/components/voice-mobile/voice-message/voice-message.component.html
app/frontend-healthier-me/src/app/services/endpoint/endpoint.service.ts

- Formdata was previously used to include both text and audio in one HTTP request. Since the audio and text is now separated, changing to JSON is better.
- It allows us to test using Postman more easily
- Added Account class (username, password)
- Updated Payload class to (username, exp)
- Encodes only username and exp (password has been removed)
- Adjusted font size slider
- Added logging print statements for endpoints

Update input type to json and JWT encode

---

infra/main.bicep

Commented out Application Insights for App Service. Instead, using Application Insights for APIM instead.

Commented out app insights for app service

---

app/backend/app.py
app/backend/approaches/chatreadretrieveread.py

Change variable name to match the one in .env file
Fix token count by adding back missing tokens

change variable name and fix token count

---

app/backend/approaches/chatreadretrieveread.py
app/backend/models/apilog.py
app/backend/utils/response_handler.py

- Added custom properties to the logs
- Separated token counts to input and output

make changes to logging

---

.github/dependabot.yml
app/frontend/src/app/pages/chat/chat.component.ts

- Ignore dependency. Reason in #201 
- Potential fix to issue #204

Potential fix for websocket close bug and ignore dependency

---

.github/dependabot.yml
app/backend/requirements.txt

Update and ignore dependencies

---

app/backend/blueprints/backend_blueprint/transcription.py
app/frontend/src/app/components/voice-mobile/voice-microphone/voice-microphone.component.ts
app/frontend/src/app/services/chat-message/chat-message.service.ts
app/frontend/src/app/services/convo-broker/convo-broker.service.ts

Removed closure of websocket from backend competely
- To check whether if the bug is caused by our code
- Remove some console log
- Change playing of start audio after mic has been activated

Temporary fix to websocket closure bug

---

app/backend/blueprints/backend_blueprint/voice.py
app/frontend/src/app/components/voice-mobile/voice-mobile.component.html
app/frontend/src/app/components/voice-mobile/voice-mobile.component.ts
app/frontend/src/app/services/convo-broker/convo-broker.service.ts
app/frontend/src/app/services/endpoint/endpoint.service.ts

fix issue of voice error not displaying in UI

---

app/backend/blueprints/backend_blueprint/chat.py
app/backend/blueprints/backend_blueprint/voice.py
app/backend/models/apilog.py
app/backend/utils/response_handler.py

Added logging for time taken for first stream to be sent

added logs for the time taken for first stream to be sent
